
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_snowflake_artifacts'
version: '1.0.0'
config-version: 2

profile: 'dbt_snowflake_artifacts'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end:
    - "{{ dbt-snowflake-artifacts.upload_artifacts_wrapper() }}"

models:
  dbt_snowflake_artifacts:
    # artifacts destination
    artifacts:
        +schema: artifacts
        materialized: table
        +enabled: "{{ target.name in [var('target_dev'), var('target_prod')] }}"

    +grants:
      select: "[ {{ var('transformer_role') }}, {{ var('reporter_role') }} ]"

vars:
  #business critical
  snowflake_contract_rate: "{{ env_var('SNOWFLAKE_CONTRACT_RATE', 4) }}"
  target_dev: "{{ env_var('TARGET_DEV', 'dev') }}"
  target_prod: "{{ env_var('TARGET_PROD', 'prod') }}"
  transformer_role: "{{ env_var('TRANSFORMER_ROLE', 'TRANSFORMER_ROLE') }}"
  reporter_role: "{{ env_var('REPORTER_ROLE', 'REPORTER_ROLE') }}"
